import axios from "axios";
import Head from "next/head";
import Script from "next/script";
import { useEffect } from "react";
import "slick-carousel/slick/slick-theme.css";
import "slick-carousel/slick/slick.css";
import { AuthProvider } from "../contexts/AuthContext";
import "../styles/globals.css";
// axios.defaults.baseURL = 'https://logoipsum-server-production.up.railway.app/api/v1';
axios.defaults.baseURL = 'http://localhost:5000/api/v1';
axios.interceptors.response.use(function (response) {
  return response;
}, function (error) {
  if (Number(error.response.status) === 401) {
    localStorage.clear();
    window.location.href = '/login';
  }
  return Promise.reject(error);
});

function MyApp({ Component, pageProps }) {
  useEffect(() => {
    axios.defaults.headers.common['Authorization'] = `Bearer ${ localStorage.getItem("token") }`;
  }, []);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT"
          crossOrigin="anonymous"
        ></link>
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossOrigin="anonymous"
        ></link>
        <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet"></link>
      </Head>
      <AuthProvider>
        <Component {...pageProps} />
      </AuthProvider>
      <Script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossOrigin="anonymous"
      ></Script>
      <Script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></Script>
    </div>
  );
}

export default MyApp;
